# Cálculo Numérico: Sistemas Lineares
## Lista de exercícios: sistemas lineares e implementação numérica

**Aluno: Luiz Ricardo Salles**  
**Turma: Tarde**  
**Professora: Raquel Jahara Lobosco**

Resoluções dos exercícios 1 a 5 do arquivo `calculo_numerico-atividade-5-10.pdf`.
As respostas conceituais e as etapas manuais aparecem nas células de texto; as implementações estão comentadas e acompanhadas dos resultados.

Para reproduzir os cálculos no Google Colab, execute as células de código na ordem em que aparecem. A única biblioteca utilizada é o NumPy.

## 1. Sistemas lineares na forma matricial

Em $A\mathbf{x}=\mathbf{b}$, cada linha de $A$ reúne os coeficientes de uma equação, na mesma ordem das incógnitas do vetor $\mathbf{x}$. O vetor $\mathbf{b}$ reúne os termos independentes.

### a)

$$\begin{cases}2x+y=7,\\x-3y=-5.\end{cases}$$

$$
\underbrace{\begin{bmatrix}2&1\\1&-3\end{bmatrix}}_{A}
\underbrace{\begin{bmatrix}x\\y\end{bmatrix}}_{\mathbf{x}}
=\underbrace{\begin{bmatrix}7\\-5\end{bmatrix}}_{\mathbf{b}}.
$$

$A$ é a matriz dos coeficientes de ordem $2\times2$; $\mathbf{x}$ é o vetor de incógnitas; $\mathbf{b}$ é o vetor independente.

### b)

$$\begin{cases}x+2y-z=2,\\3x-y+2z=9,\\2x+y+z=7.\end{cases}$$

$$
\underbrace{\begin{bmatrix}1&2&-1\\3&-1&2\\2&1&1\end{bmatrix}}_{A}
\underbrace{\begin{bmatrix}x\\y\\z\end{bmatrix}}_{\mathbf{x}}
=\underbrace{\begin{bmatrix}2\\9\\7\end{bmatrix}}_{\mathbf{b}}.
$$

$A$ é a matriz dos coeficientes de ordem $3\times3$; $\mathbf{x}$ é o vetor de incógnitas; $\mathbf{b}$ é o vetor independente.

## 2. Eliminação de Gauss: resolução manual

$$\begin{cases}2x+y-z=8,\\-3x-y+2z=-11,\\-2x+y+2z=-3.\end{cases}$$

**Matriz aumentada inicial:**

$$\left[\begin{array}{rrr|r}2&1&-1&8\\-3&-1&2&-11\\-2&1&2&-3\end{array}\right].$$

**Etapa 1:** usando o pivô $2$, fazemos $L_2\leftarrow L_2+\frac32L_1$:

$$\left[\begin{array}{rrr|r}2&1&-1&8\\0&\frac12&\frac12&1\\-2&1&2&-3\end{array}\right].$$

**Etapa 2:** fazemos $L_3\leftarrow L_3+L_1$:

$$\left[\begin{array}{rrr|r}2&1&-1&8\\0&\frac12&\frac12&1\\0&2&1&5\end{array}\right].$$

**Etapa 3:** usando o pivô $\frac12$, fazemos $L_3\leftarrow L_3-4L_2$:

$$\left[\begin{array}{rrr|r}2&1&-1&8\\0&\frac12&\frac12&1\\0&0&-1&1\end{array}\right].$$

**Substituição regressiva:**

$$-z=1\quad\Rightarrow\quad z=-1.$$
$$\frac12y+\frac12z=1\quad\Rightarrow\quad y=2-z=3.$$
$$2x+y-z=8\quad\Rightarrow\quad x=\frac{8-y+z}{2}=\frac{8-3-1}{2}=2.$$

**Resposta:** $\boxed{(x,y,z)=(2,3,-1)}$.

Conferindo nas equações originais:

$$2(2)+3-(-1)=8,$$
$$-3(2)-3+2(-1)=-11,$$
$$-2(2)+3+2(-1)=-3.$$

Todos os pivôs são não nulos, portanto o sistema possui solução única.

## 3. Número de soluções

### a) Infinitas soluções

$$\begin{cases}x+y=3,\\2x+2y=6.\end{cases}$$

Aplicando $L_2\leftarrow L_2-2L_1$:

$$\left[\begin{array}{rr|r}1&1&3\\2&2&6\end{array}\right]
\longrightarrow
\left[\begin{array}{rr|r}1&1&3\\0&0&0\end{array}\right].$$

A última linha representa $0=0$. Resta uma equação independente para duas incógnitas, com uma variável livre. Tomando $y=t$, obtemos

$$\boxed{(x,y)=(3-t,t),\quad t\in\mathbb{R}.}$$

O sistema é **possível e indeterminado**, pois $\operatorname{posto}(A)=\operatorname{posto}([A|b])=1<2$.

### b) Nenhuma solução

$$\begin{cases}x+y=3,\\2x+2y=7.\end{cases}$$

Aplicando $L_2\leftarrow L_2-2L_1$:

$$\left[\begin{array}{rr|r}1&1&3\\2&2&7\end{array}\right]
\longrightarrow
\left[\begin{array}{rr|r}1&1&3\\0&0&1\end{array}\right].$$

A última linha representa a contradição $0=1$. Logo, **não há solução**: o sistema é **impossível**, pois $\operatorname{posto}(A)=1$ e $\operatorname{posto}([A|b])=2$.

### c) Solução única

$$\begin{cases}x+y=3,\\2x-y=0.\end{cases}$$

Aplicando $L_2\leftarrow L_2-2L_1$:

$$\left[\begin{array}{rr|r}1&1&3\\2&-1&0\end{array}\right]
\longrightarrow
\left[\begin{array}{rr|r}1&1&3\\0&-3&-6\end{array}\right].$$

Em seguida, $L_2\leftarrow-\frac13L_2$ e $L_1\leftarrow L_1-L_2$:

$$\left[\begin{array}{rr|r}1&1&3\\0&1&2\end{array}\right]
\longrightarrow
\left[\begin{array}{rr|r}1&0&1\\0&1&2\end{array}\right].$$

Assim, $\boxed{(x,y)=(1,2)}$. O sistema é **possível e determinado**, pois $\operatorname{posto}(A)=\operatorname{posto}([A|b])=2$, igual ao número de incógnitas.

## 4. Eliminação de Gauss sem pivoteamento em Python

Para cada pivô $a_{kk}$, o multiplicador é $m_{ik}=a_{ik}/a_{kk}$ e a operação é $L_i\leftarrow L_i-m_{ik}L_k$. Ao final, o sistema triangular é resolvido de baixo para cima:

$$x_i=\frac{b_i-\sum_{j=i+1}^{n-1}a_{ij}x_j}{a_{ii}}.$$

A função abaixo forma a matriz aumentada, elimina os elementos abaixo dos pivôs e aplica substituição regressiva. **Não realiza trocas de linhas.** A verificação de pivôs nulos ou menores que a tolerância absoluta de $10^{-12}$ evita divisões numericamente problemáticas. Uma interrupção por esse motivo não significa, por si só, que o sistema não tenha solução; pode ser necessário pivoteamento.

In [1]:
import numpy as np

np.set_printoptions(precision=8, suppress=True)

def gauss_sem_pivoteamento(A, b, mostrar_etapas=False, tolerancia=1e-12):
    """Resolve Ax=b por eliminação de Gauss, sem trocar linhas."""
    # Cópias em ponto flutuante preservam as entradas e permitem frações.
    A = np.array(A, dtype=float, copy=True)
    b = np.array(b, dtype=float, copy=True)

    if A.ndim != 2 or A.shape[0] != A.shape[1] or A.shape[0] == 0:
        raise ValueError("A deve ser uma matriz quadrada não vazia.")
    n = A.shape[0]
    if b.shape != (n,):
        raise ValueError("b deve ser um vetor unidimensional de tamanho n.")
    if not np.isfinite(A).all() or not np.isfinite(b).all():
        raise ValueError("A e b devem conter apenas valores finitos.")
    if not np.isfinite(tolerancia) or tolerancia <= 0:
        raise ValueError("A tolerância deve ser positiva e finita.")

    # Formação da matriz aumentada [A | b].
    M = np.column_stack((A, b))
    if mostrar_etapas:
        print("Matriz aumentada inicial:\n", M)

    # Eliminação dos elementos abaixo da diagonal principal.
    for k in range(n - 1):
        if abs(M[k, k]) <= tolerancia:
            raise ValueError(f"Pivô nulo ou muito pequeno na linha {k + 1}.")
        for i in range(k + 1, n):
            multiplicador = M[i, k] / M[k, k]
            M[i, k:] -= multiplicador * M[k, k:]
            M[i, k] = 0.0  # Zero da eliminação, explícito para apresentação.
            if mostrar_etapas:
                print(f"\nL{i + 1} <- L{i + 1} - ({multiplicador:.8g}) * L{k + 1}")
                print(M)

    # Substituição regressiva: calcula a última incógnita primeiro.
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        if abs(M[i, i]) <= tolerancia:
            raise ValueError(f"Pivô nulo ou muito pequeno na linha {i + 1}.")
        soma = np.dot(M[i, i + 1:n], x[i + 1:n])
        x[i] = (M[i, n] - soma) / M[i, i]

    return x

### Teste com o sistema do exercício 2

O NumPy é utilizado como referência independente. O resíduo $A\mathbf{x}-\mathbf{b}$ permite conferir se a solução satisfaz o sistema original.

In [2]:
# Coeficientes e termos independentes do exercício 2.
A2 = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]], dtype=float)
b2 = np.array([8, -11, -3], dtype=float)

x_gauss = gauss_sem_pivoteamento(A2, b2, mostrar_etapas=True)
x_numpy = np.linalg.solve(A2, b2)
residuo2 = A2 @ x_gauss - b2

print("\nSolução por Gauss:", x_gauss)
print("Solução pelo NumPy:", x_numpy)
print("Diferença máxima absoluta:", np.max(np.abs(x_gauss - x_numpy)))
print("Resíduo A @ x - b:", residuo2)
print("Norma infinita do resíduo:", np.linalg.norm(residuo2, ord=np.inf))
print("Resultados coincidem?", np.allclose(x_gauss, x_numpy, rtol=1e-10, atol=1e-12))

# Verificações contra a resposta manual e a solução de referência.
assert np.allclose(x_gauss, [2, 3, -1], rtol=1e-10, atol=1e-12)
assert np.allclose(x_gauss, x_numpy, rtol=1e-10, atol=1e-12)
assert np.linalg.norm(residuo2, ord=np.inf) < 1e-10

Matriz aumentada inicial:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

L2 <- L2 - (-1.5) * L1
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [-2.   1.   2.  -3. ]]

L3 <- L3 - (-1) * L1
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

L3 <- L3 - (4) * L2
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]

Solução por Gauss: [ 2.  3. -1.]
Solução pelo NumPy: [ 2.  3. -1.]
Diferença máxima absoluta: 1.2212453270876722e-15
Resíduo A @ x - b: [0. 0. 0.]
Norma infinita do resíduo: 0.0
Resultados coincidem? True


**Interpretação:** a implementação retorna $(2,3,-1)$, de acordo com a resolução manual e com `numpy.linalg.solve`. Diferenças da ordem de $10^{-15}$ podem aparecer por arredondamento em ponto flutuante. O resíduo nulo ou muito próximo de zero confirma que as equações são satisfeitas numericamente. Neste sistema, os pivôs $2$, $1/2$ e $-1$ permitem concluir a eliminação sem troca de linhas.

## 5. Modelo de balanço térmico

$$\begin{bmatrix}4&-1&0\\-1&4&-1\\0&-1&3\end{bmatrix}
\begin{bmatrix}T_1\\T_2\\T_3\end{bmatrix}
=\begin{bmatrix}15\\10\\10\end{bmatrix}.$$

### a) Resolução manual

As equações são $4T_1-T_2=15$, $-T_1+4T_2-T_3=10$ e $-T_2+3T_3=10$.

**Matriz aumentada inicial:**

$$\left[\begin{array}{rrr|r}4&-1&0&15\\-1&4&-1&10\\0&-1&3&10\end{array}\right].$$

**Etapa 1:** $L_2\leftarrow L_2+\frac14L_1$:

$$\left[\begin{array}{rrr|r}4&-1&0&15\\0&\frac{15}{4}&-1&\frac{55}{4}\\0&-1&3&10\end{array}\right].$$

O primeiro elemento de $L_3$ já é zero.

**Etapa 2:** $L_3\leftarrow L_3+\frac4{15}L_2$:

$$3-\frac4{15}=\frac{41}{15},\qquad
10+\frac4{15}\frac{55}{4}=\frac{41}{3}.$$

$$\left[\begin{array}{rrr|r}4&-1&0&15\\0&\frac{15}{4}&-1&\frac{55}{4}\\0&0&\frac{41}{15}&\frac{41}{3}\end{array}\right].$$

**Substituição regressiva:**

$$T_3=\frac{41/3}{41/15}=5.$$
$$\frac{15}{4}T_2-T_3=\frac{55}{4}
\quad\Rightarrow\quad T_2=\frac{55+4T_3}{15}=5.$$
$$4T_1-T_2=15\quad\Rightarrow\quad T_1=\frac{15+T_2}{4}=5.$$

**Resposta:** $\boxed{T_1=T_2=T_3=5}$, na unidade de temperatura adotada pelo modelo (não especificada no enunciado).

Conferência: $4(5)-5=15$, $-5+4(5)-5=10$ e $-5+3(5)=10$.

Os três pivôs são não nulos. Além disso, como usamos somente somas de múltiplos de linhas, o determinante é o produto dos pivôs:

$$\det(A)=4\cdot\frac{15}{4}\cdot\frac{41}{15}=41\ne0.$$

Portanto, a solução é única.

### b) Implementação em Python

Reutilizamos a função de Gauss e verificamos o resultado com o NumPy e com o resíduo do sistema.

In [3]:
# Matriz do modelo térmico e vetor independente.
A5 = np.array([[4, -1, 0], [-1, 4, -1], [0, -1, 3]], dtype=float)
b5 = np.array([15, 10, 10], dtype=float)

T = gauss_sem_pivoteamento(A5, b5, mostrar_etapas=True)
T_numpy = np.linalg.solve(A5, b5)
residuo5 = A5 @ T - b5

print("\nTemperaturas calculadas:")
for i, temperatura in enumerate(T, start=1):
    print(f"T{i} = {temperatura:.8f}")
print("Solução pelo NumPy:", T_numpy)
print("A @ T:", A5 @ T)
print("Resíduo A @ T - b:", residuo5)
print("Norma infinita do resíduo:", np.linalg.norm(residuo5, ord=np.inf))
print("Resultados coincidem?", np.allclose(T, T_numpy, rtol=1e-10, atol=1e-12))

assert np.allclose(T, [5, 5, 5], rtol=1e-10, atol=1e-12)
assert np.allclose(T, T_numpy, rtol=1e-10, atol=1e-12)
assert np.linalg.norm(residuo5, ord=np.inf) < 1e-10

Matriz aumentada inicial:
 [[ 4. -1.  0. 15.]
 [-1.  4. -1. 10.]
 [ 0. -1.  3. 10.]]

L2 <- L2 - (-0.25) * L1
[[ 4.   -1.    0.   15.  ]
 [ 0.    3.75 -1.   13.75]
 [ 0.   -1.    3.   10.  ]]

L3 <- L3 - (0) * L1
[[ 4.   -1.    0.   15.  ]
 [ 0.    3.75 -1.   13.75]
 [ 0.   -1.    3.   10.  ]]

L3 <- L3 - (-0.26666667) * L2
[[ 4.         -1.          0.         15.        ]
 [ 0.          3.75       -1.         13.75      ]
 [ 0.          0.          2.73333333 13.66666667]]

Temperaturas calculadas:
T1 = 5.00000000
T2 = 5.00000000
T3 = 5.00000000
Solução pelo NumPy: [5. 5. 5.]
A @ T: [15. 10. 10.]
Resíduo A @ T - b: [0. 0. 0.]
Norma infinita do resíduo: 0.0
Resultados coincidem? True


**Interpretação:** as três temperaturas desconhecidas são iguais a $5$. Substituí-las no modelo produz o vetor $(15,10,10)^T$, confirmando o balanço térmico representado pelas três equações. O resultado computacional coincide com a resolução manual; resíduos muito pequenos decorrem do arredondamento numérico.